# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XWRealmSwiftDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

	pod 'Realm'
	pod 'RealmSwift'

  target 'XWRealmSwiftDemoTests' do
    inherit! :search_paths
	pod 'Realm'
	pod 'RealmSwift'
  end

end
