# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XWLoadImageToolDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

 pod 'SDWebImage'	

  target 'XWLoadImageToolDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'XWLoadImageToolDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
